//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autinaut.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autinaut.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück Button.
        /// </summary>
        public static string BackButtonHelpText {
            get {
                return ResourceManager.GetString("BackButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string BackButtonName {
            get {
                return ResourceManager.GetString("BackButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Gefühl.
        /// </summary>
        public static string EmotionItemPageTitle {
            get {
                return ResourceManager.GetString("EmotionItemPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Gefühle.
        /// </summary>
        public static string EmotionItemsPageTitle {
            get {
                return ResourceManager.GetString("EmotionItemsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibe die Situation.
        /// </summary>
        public static string HintInputSituation {
            get {
                return ResourceManager.GetString("HintInputSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibe Deinen Erfolg.
        /// </summary>
        public static string HintInputSuccess {
            get {
                return ResourceManager.GetString("HintInputSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei Dein Autinaut.
        /// </summary>
        public static string InfoPageTitle {
            get {
                return ResourceManager.GetString("InfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App entstand im Zuge des FASTER-Programms des Universitätsklinikums Freiburg. Sie richtet sich in erster Linie an Menschen im Autismusspektrum..
        /// </summary>
        public static string InfoTextPartOne {
            get {
                return ResourceManager.GetString("InfoTextPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterhin kann es sich als nützlich herausstellen, sich seine Erfolge niederzuschreiben. Diese kannst Du Dir dann immer &apos;vor Augen halten&apos;..
        /// </summary>
        public static string InfoTextPartThree {
            get {
                return ResourceManager.GetString("InfoTextPartThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In vielen Situationen entstehen Gefühle. Halte eines Deiner sieben Grundgefühle (nach Paul Ekman) in verschiedenen Situationen fest. Die Protokollierung kann Dir dabei helfen, Dich mit dem Thema Gefühlserkennung und Gefühlsbennenung auseinanderzusetzen. Zusätzlich kannst Du die Ausprägung des Gefühls mit einer sogenannten Affektbilanz verknüpfen..
        /// </summary>
        public static string InfoTextPartTwo {
            get {
                return ResourceManager.GetString("InfoTextPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefühl.
        /// </summary>
        public static string LabelFeeling {
            get {
                return ResourceManager.GetString("LabelFeeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei Dein Autinaut. Klicke auf das Icon in der oberen Leiste um Deinen ersten Eintrag zu erstellen..
        /// </summary>
        public static string LabelInitialTextPartOne {
            get {
                return ResourceManager.GetString("LabelInitialTextPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke anschließend bei Bedarf auf einen vorhandenen Listeneintrag um ihn zu editieren oder zu löschen..
        /// </summary>
        public static string LabelInitialTextPartTwo {
            get {
                return ResourceManager.GetString("LabelInitialTextPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Affektbilanz.
        /// </summary>
        public static string LabelNegativeAffect {
            get {
                return ResourceManager.GetString("LabelNegativeAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Affektbilanz.
        /// </summary>
        public static string LabelPositiveAffect {
            get {
                return ResourceManager.GetString("LabelPositiveAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situation.
        /// </summary>
        public static string LabelSituation {
            get {
                return ResourceManager.GetString("LabelSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Feedback Zu Autinaut.
        /// </summary>
        public static string MailSubjectText {
            get {
                return ResourceManager.GetString("MailSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte trage eine Situation ein..
        /// </summary>
        public static string NotificationSituationText {
            get {
                return ResourceManager.GetString("NotificationSituationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte trage einen Erfolg ein..
        /// </summary>
        public static string NotificationSuccessText {
            get {
                return ResourceManager.GetString("NotificationSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldung.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string SfButtonAutomationPropertiesNameDelete {
            get {
                return ResourceManager.GetString("SfButtonAutomationPropertiesNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string SfButtonAutomationPropertiesNameSave {
            get {
                return ResourceManager.GetString("SfButtonAutomationPropertiesNameSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besonderen Dank an Jan Charpa.
        /// </summary>
        public static string SpecialThanx {
            get {
                return ResourceManager.GetString("SpecialThanx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Erfolg.
        /// </summary>
        public static string SuccessItemPageTitle {
            get {
                return ResourceManager.GetString("SuccessItemPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Erfolge.
        /// </summary>
        public static string SuccessItemsPageTitle {
            get {
                return ResourceManager.GetString("SuccessItemsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefühle.
        /// </summary>
        public static string TabTitleFeelings {
            get {
                return ResourceManager.GetString("TabTitleFeelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TabTitleInfo {
            get {
                return ResourceManager.GetString("TabTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolge.
        /// </summary>
        public static string TabTitleSuccesses {
            get {
                return ResourceManager.GetString("TabTitleSuccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Affektbilanz liegt bei {0} %..
        /// </summary>
        public static string TextActualAffectBilance {
            get {
                return ResourceManager.GetString("TextActualAffectBilance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Affektbilanz liegt bei 0 %..
        /// </summary>
        public static string TextAffectBilance {
            get {
                return ResourceManager.GetString("TextAffectBilance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail wird auf diesem Gerät nicht unterstützt..
        /// </summary>
        public static string TextAlertMailNotSupportedText {
            get {
                return ResourceManager.GetString("TextAlertMailNotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion wird nicht unterstützt.
        /// </summary>
        public static string TextAlertMailNotSupportedTitle {
            get {
                return ResourceManager.GetString("TextAlertMailNotSupportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback senden.
        /// </summary>
        public static string TextButtonFeedback {
            get {
                return ResourceManager.GetString("TextButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wut.
        /// </summary>
        public static string TextEmotionAnger {
            get {
                return ResourceManager.GetString("TextEmotionAnger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verachtung.
        /// </summary>
        public static string TextEmotionContempt {
            get {
                return ResourceManager.GetString("TextEmotionContempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekel.
        /// </summary>
        public static string TextEmotionDisgust {
            get {
                return ResourceManager.GetString("TextEmotionDisgust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angst.
        /// </summary>
        public static string TextEmotionFear {
            get {
                return ResourceManager.GetString("TextEmotionFear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freude.
        /// </summary>
        public static string TextEmotionJoy {
            get {
                return ResourceManager.GetString("TextEmotionJoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trauer.
        /// </summary>
        public static string TextEmotionSadness {
            get {
                return ResourceManager.GetString("TextEmotionSadness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überraschung.
        /// </summary>
        public static string TextEmotionSurprise {
            get {
                return ResourceManager.GetString("TextEmotionSurprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausnahmefehler.
        /// </summary>
        public static string TextExceptionTtitle {
            get {
                return ResourceManager.GetString("TextExceptionTtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string TextSfButtonDelete {
            get {
                return ResourceManager.GetString("TextSfButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string TextSfButtonSave {
            get {
                return ResourceManager.GetString("TextSfButtonSave", resourceCulture);
            }
        }
    }
}
